# NumPy - Numerical Python

![](numpy.JPG)

__*NumPy is a library for the Python programming language, adding support for large,multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.The fundamental package for scientific computing with Python.In 2005, Travis Oliphant created NumPy by incorporating features of the competing Numarray into Numeric, with extensive modifications. NumPy is open-source software and has many contributors.*__

# *Ndarray*

*__The core functionality of NumPy is its "ndarray", for n-dimensional array, data structure. These arrays are strided views on memory. In contrast to Python's built-in list data structure, these arrays are HOMOGENEOUSLY typed: all elements of a single array must be of the same type.__*

![](nda.png)

# *_NOTE_*
* In NumPy, each dimension is called an **axis**.
* The number of axes is called the **rank**.
* An array's list of axis lengths is called the **shape** of the array.
* The **"rank is equal to the shape's length"**.
* The **size** of an array is the total number of elements, which is the product of all axis lengths.

In [1]:
import numpy as np #Importing numpy package
np.__version__ # Version of Numpy Package 

'1.15.1'

In [2]:
array_1D=np.array([7,2,9,10])         # Creating 1Dimensional numpy array
array_2D=np.array([[5.2,3.0,4.5],    # Creating 2Dimensional numpy array
                    [9.1,0.1,0.3]
                   ])
array_3D=np.array([                   # Creating 3Dimensional numpy array
                   [ 
                    [1,4,7],
                    [2,9,7],
                    [1,3,0],
                    [9,6,9]
                   ],
                   [
                    [2,3,4],
                    [1,3,5],
                    [0,1,2],
                    [8,6,8]
                   ]    
                  ])

__Since Ndarray is homogeneous in nature.All the elements inside them are of same datatype__

In [3]:
print('1D array\n',array_1D ,'\n2D array\n',array_2D,'\n3D array\n',array_3D)

1D array
 [ 7  2  9 10] 
2D array
 [[5.2 3.  4.5]
 [9.1 0.1 0.3]] 
3D array
 [[[1 4 7]
  [2 9 7]
  [1 3 0]
  [9 6 9]]

 [[2 3 4]
  [1 3 5]
  [0 1 2]
  [8 6 8]]]


In [4]:
print('Shape of 1D array --->',array_1D.shape,'\nShape of 2D array --->',array_2D.shape,'\nShape of 3D array --->',array_3D.shape)

Shape of 1D array ---> (4,) 
Shape of 2D array ---> (2, 3) 
Shape of 3D array ---> (2, 4, 3)


In [5]:
print('Datatype of 1D array --->',array_1D.dtype,'\nDatatype  of 2D array --->',array_2D.dtype,'\nDatatype  of 3D array --->',array_3D.dtype)

Datatype of 1D array ---> int32 
Datatype  of 2D array ---> float64 
Datatype  of 3D array ---> int32


In [6]:
print('Number of Dimensions of 1D array --->',array_1D.ndim,'\nNumber of Dimension  of 2D array --->',array_2D.ndim,'\nNumber of Dimension  of 3D array --->',array_3D.ndim)

Number of Dimensions of 1D array ---> 1 
Number of Dimension  of 2D array ---> 2 
Number of Dimension  of 3D array ---> 3


In [7]:
print('Type of 1D array --->',type(array_1D),'\nType  of 2D array --->',type(array_2D),'\nType  of 3D array --->',type(array_3D))

Type of 1D array ---> <class 'numpy.ndarray'> 
Type  of 2D array ---> <class 'numpy.ndarray'> 
Type  of 3D array ---> <class 'numpy.ndarray'>


In [8]:
print('Number of Elements in 1D array --->',array_1D.size,'\nNumber of Elements in 2D array --->',array_2D.size,'\nNumber of Elements in 3D array --->',array_3D.size)

Number of Elements in 1D array ---> 4 
Number of Elements in 2D array ---> 6 
Number of Elements in 3D array ---> 24


In [9]:
print('Size in Bytes of Each element in 1D array --->',array_1D.itemsize,array_1D.dtype,'\nSize in Bytes of Each element in 2D array --->',array_2D.itemsize,array_2D.dtype,'\nSize in Bytes of Each element in 3D array --->',array_3D.itemsize,array_3D.dtype)

Size in Bytes of Each element in 1D array ---> 4 int32 
Size in Bytes of Each element in 2D array ---> 8 float64 
Size in Bytes of Each element in 3D array ---> 4 int32


In [10]:
print('Total Size in Bytes of 1D array --->',array_1D.nbytes,array_1D.dtype,'\nTotal Size in Bytes of 2D array --->',array_2D.nbytes,array_2D.dtype,'\nTotal Size in Bytes of 3D array --->',array_3D.nbytes,array_3D.dtype)

Total Size in Bytes of 1D array ---> 16 int32 
Total Size in Bytes of 2D array ---> 48 float64 
Total Size in Bytes of 3D array ---> 96 int32


### np.zeros

In [11]:
array_zero=np.zeros((4,6)) #Arrays with zeros
print(array_zero,'--->',array_zero.dtype)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] ---> float64


In [12]:
array_likezero=np.zeros_like(array_2D)
print(array_likezero,'--->',array_likezero.dtype)

[[0. 0. 0.]
 [0. 0. 0.]] ---> float64


### np.ones

In [13]:
array_ones=np.ones((4,6)) #Arrays with ones
print(array_ones,'--->',array_ones.dtype)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]] ---> float64


In [14]:
array_likeones=np.ones_like(array_2D)
print(array_likeones,'--->',array_likeones.dtype)

[[1. 1. 1.]
 [1. 1. 1.]] ---> float64


### np.identity

In [15]:
array_identity=np.identity(6,np.int64) # identity matrix with 1 being in diagonal
print(array_identity,'--->',array_identity.dtype)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]] ---> int64


### np.full
Creates an array of the given shape initialized with the given value. Here's a 3x5 matrix full of value sine(-1)

In [16]:
array_full=np.full((3,5),np.sin(-1))
print(array_full,'--->',array_full.dtype)

[[-0.84147098 -0.84147098 -0.84147098 -0.84147098 -0.84147098]
 [-0.84147098 -0.84147098 -0.84147098 -0.84147098 -0.84147098]
 [-0.84147098 -0.84147098 -0.84147098 -0.84147098 -0.84147098]] ---> float64


In [17]:
array_fulllike=np.full_like(array_1D,5)
print(array_fulllike,'--->',array_fulllike.dtype)

[5 5 5 5] ---> int32


### np.empty
An uninitialized 2x4 array (its content is not predictable, as it is whatever is in memory at that point):

In [18]:
array_empty=np.empty((2,4))
print(array_empty,'--->',array_empty.dtype)

[[0.00e+000 0.00e+000 0.00e+000 0.00e+000]
 [0.00e+000 6.54e-321 0.00e+000 0.00e+000]] ---> float64


In [19]:
array_emptylike=np.empty_like(array_1D)
print(array_emptylike,'--->',array_emptylike.dtype)

[-766221184        613          0          0] ---> int32


### np.arange
You can create an ndarray using NumPy's range function, which is similar to python's built-in range function:

In [20]:
np.arange(3,10,2)

array([3, 5, 7, 9])

### np.linspace
The linspace function returns an array containing a specific number of points evenly distributed between two values (note that the maximum value is included, contrary to arange):

In [21]:
np.linspace(100,400,25)

array([100. , 112.5, 125. , 137.5, 150. , 162.5, 175. , 187.5, 200. ,
       212.5, 225. , 237.5, 250. , 262.5, 275. , 287.5, 300. , 312.5,
       325. , 337.5, 350. , 362.5, 375. , 387.5, 400. ])

### np.random


Here is a 3x3 matrix initialized with random floats between 0 and 1 (uniform distribution)

In [22]:
np.random.rand(3,3)

array([[0.23491304, 0.71947743, 0.37360799],
       [0.86717102, 0.82053791, 0.02771375],
       [0.77871116, 0.38631342, 0.91566568]])

Here's a 3x4 matrix containing random floats sampled from a univariate normal distribution (Gaussian distribution) of mean 0 and variance 1

In [23]:
np.random.randn(3,3)

array([[ 0.25713908, -1.05007245, -0.07239964],
       [ 0.69028792,  1.10115722, -1.6136151 ],
       [-0.97733731, -1.7358142 ,  2.32660562]])

![](random.JPG)

In [24]:
np.random.randint(1,100,(3,3))

array([[95, 82, 11],
       [37, 86, 25],
       [93, 86,  4]])

### Reshape
The reshape function returns a new ndarray object pointing at the same data. This means that modifying one array will also modify the other.

In [25]:
arr_reshape=np.reshape(array_3D,(2,12))
print(arr_reshape)

[[1 4 7 2 9 7 1 3 0 9 6 9]
 [2 3 4 1 3 5 0 1 2 8 6 8]]


In [26]:
array_3D

array([[[1, 4, 7],
        [2, 9, 7],
        [1, 3, 0],
        [9, 6, 9]],

       [[2, 3, 4],
        [1, 3, 5],
        [0, 1, 2],
        [8, 6, 8]]])

In [27]:
arr_reshape[1,2]=555
arr_reshape

array([[  1,   4,   7,   2,   9,   7,   1,   3,   0,   9,   6,   9],
       [  2,   3, 555,   1,   3,   5,   0,   1,   2,   8,   6,   8]])

In [28]:
array_3D

array([[[  1,   4,   7],
        [  2,   9,   7],
        [  1,   3,   0],
        [  9,   6,   9]],

       [[  2,   3, 555],
        [  1,   3,   5],
        [  0,   1,   2],
        [  8,   6,   8]]])

### Ravel(EFFICIENT)
Finally, the ravel function returns a new one-dimensional ndarray that also points to the same data:
*__Changes in arr_ravel affect and changes are also made in arr_reshape__*

In [29]:
arr_ravel=np.ravel(arr_reshape)
arr_ravel,arr_ravel.shape

(array([  1,   4,   7,   2,   9,   7,   1,   3,   0,   9,   6,   9,   2,
          3, 555,   1,   3,   5,   0,   1,   2,   8,   6,   8]),
 (24,))

### Flatten(SAFE)
The resulting array in a new copy of the array.*__Changes in arr_flatten will not affect and no changes are made in arr_flatten__*

In [30]:
arr_flatten=array_2D.flatten()
arr_flatten,arr_flatten.shape

(array([5.2, 3. , 4.5, 9.1, 0.1, 0.3]), (6,))

### Max, Argmax, Min, Argmin

In [31]:
array_3D.max()  # Maximum value of that array

555

In [32]:
array_3D.argmax()  # The index that is reffering to the maximum value of the array

14

In [33]:
array_3D.min() # Minimum value of that array

0

In [34]:
array_3D.argmin()  #The index that is reffering to the minimum value of the array

8

### Transpose

In [35]:
array_3D,array_3D.shape   # Transpose of the matrix.The rows and columns get interchanged

(array([[[  1,   4,   7],
         [  2,   9,   7],
         [  1,   3,   0],
         [  9,   6,   9]],
 
        [[  2,   3, 555],
         [  1,   3,   5],
         [  0,   1,   2],
         [  8,   6,   8]]]),
 (2, 4, 3))

In [36]:
array_3D.T,array_3D.T.shape

(array([[[  1,   2],
         [  2,   1],
         [  1,   0],
         [  9,   8]],
 
        [[  4,   3],
         [  9,   3],
         [  3,   1],
         [  6,   6]],
 
        [[  7, 555],
         [  7,   5],
         [  0,   2],
         [  9,   8]]]),
 (3, 4, 2))

# Indexing  and Slicing

![](slice.JPG)

In [37]:
Array=np.array([[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25],[30,31,32,33,34,35]
               ,[40,41,42,43,44,45],[50,51,52,53,54,55]])
print(Array)

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [38]:
red=Array[[0,2,5],2]   #Fancy Indexing
print(red)

[ 2 22 52]


In [39]:
blue=Array[3:,[0,2,5]]
print(blue)

[[30 32 35]
 [40 42 45]
 [50 52 55]]


In [40]:
yellow=Array[[0,1,2,3,4],[1,2,3,4,5]]
print(yellow)

[ 1 12 23 34 45]


# Arithmetic operations
All the usual arithmetic operators (`+`, `-`, `*`, `/`, `//`, `**`, etc.) can be used with `ndarray`s. They apply *elementwise*:

In [41]:
A = np.array([25,34,76,96])
B = np.array([56,38,24,65])
print("a + b  =", A + B)
print("a - b  =", A - B)
print("a * b  =", A * B)
print("a / b  =", A / B)
print("a // b  =", A // B)
print("a % b  =", A % B)
print("a ** b =", A ** B)
print('Exponential of A --->',np.exp(A))
print('sine value of B --->',np.sin(B))
print('cosine value of A --->',np.cos(A))
print('Logrithmic value of B--->',np.log(B))
print('Square Root value of A --->',np.sqrt(A))
print('Dot Product of A & B --->',A.dot(B))

a + b  = [ 81  72 100 161]
a - b  = [-31  -4  52  31]
a * b  = [1400 1292 1824 6240]
a / b  = [0.44642857 0.89473684 3.16666667 1.47692308]
a // b  = [0 0 3 1]
a % b  = [25 34  4 31]
a ** b = [629038657         0         0         0]
Exponential of A ---> [7.20048993e+10 5.83461743e+14 1.01480039e+33 4.92345829e+41]
sine value of B ---> [-0.521551    0.29636858 -0.90557836  0.82682868]
cosine value of A ---> [ 0.99120281 -0.84857027  0.82433133 -0.18043045]
Logrithmic value of B---> [4.02535169 3.63758616 3.17805383 4.17438727]
Square Root value of A ---> [5.         5.83095189 8.71779789 9.79795897]
Dot Product of A & B ---> 10756


**Note that the multiplication is *not* a matrix multiplication. We will discuss matrix operations below.
The arrays must have the same shape. If they do not, NumPy will apply the *broadcasting rules*.**

## BROADCASTING 

**Numpy arrays of different dimensionality can be combined in the same expression.Arrays with smaller dimension are** `Broadcasted` **to match the larger arrays,without copying data.**
* Broadcasting can often be used to replace needless data replication inside a NumPy array expression.
* Broadcationg can also be used to slice elements from different "depths" in a 3D or any other shape arrar.This is a very powerful feature of indexing

_**The main Disadvantage of Broadcasting ---> Inefficient use of memory that slows computation**_

![](Broad.JPG)

In [42]:
a=np.array([
            [0 ],
            [10],
            [20],
            [30]
           ])
b=np.array([0,1,2])
print('A\n',A,'\tB',B)

A
 [25 34 76 96] 	B [56 38 24 65]


In [43]:
print('Shape of A --->',a.shape,'\nShape of B --->',b.shape)

Shape of A ---> (4, 1) 
Shape of B ---> (3,)


In [44]:
C=a+b                # A'shape has been broadcasted to (4,3)& B's shape has been broadcasted to (4,3) and then the Matrix Addition Takes place.
print(C,'\nShape of C --->',C.shape)   
                                 

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]] 
Shape of C ---> (4, 3)


### Ellipsis (`...`)
You may also write an ellipsis (`...`) to ask that all non-specified axes be entirely included.

In [45]:
array_3D

array([[[  1,   4,   7],
        [  2,   9,   7],
        [  1,   3,   0],
        [  9,   6,   9]],

       [[  2,   3, 555],
        [  1,   3,   5],
        [  0,   1,   2],
        [  8,   6,   8]]])

In [46]:
array_3D[1,...]

array([[  2,   3, 555],
       [  1,   3,   5],
       [  0,   1,   2],
       [  8,   6,   8]])

### Stacking arrays

### vstack


In [47]:
q1 = np.full((3,4), 1.0)
q2 = np.full((4,4), 2.0)
q3 = np.full((3,4), 3.0)
q4 = np.vstack((q1, q2, q3))   # Stacks arrays Vertically
q4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

### hstack

In [48]:
q4 = np.hstack((q1, q3))       #Stacks arrays Horizontally
q4

array([[1., 1., 1., 1., 3., 3., 3., 3.],
       [1., 1., 1., 1., 3., 3., 3., 3.],
       [1., 1., 1., 1., 3., 3., 3., 3.]])

### concatenate
The concatenate function stacks arrays along any given existing axis.

In [49]:
q7 = np.concatenate((q1, q2, q3), axis=0)  # Equivalent to vstack if axis=0 and hstack if axis=1
q7

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

### stack
The stack function stacks arrays along a new axis. All arrays have to have the same shape.

In [50]:
q8 = np.stack((q1, q3))                
q8

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]])

### Splitting arrays

In [51]:
r1, r2 = np.vsplit(q7, 2)
r1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [52]:
r2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [53]:
r3,r4=np.hsplit(q7, 2)
r3

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [54]:
r4

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

**There is also a split function which splits an array along any given axis. Calling vsplit is equivalent to calling split with axis=0. There is also an hsplit function, equivalent to calling split with axis=1**

## Statistics with Numpy

In [55]:
stats=np.random.randint(1,100,(10,10))
print(stats)

[[34 72 78  2 82  2 48 17 72 10]
 [59 87 17 62 55 56 34 31 29 71]
 [55 64 70 49 81 14 63 59 73 73]
 [70 88 35 83 84 51 38 92 97 53]
 [35 59 52 43 12 60 50 52 77 32]
 [65 43 87 97 83 62 47 20 27 65]
 [80 25 86 15 82 15 20 20 87 80]
 [92 82 19 83 94 15 64 74 71 71]
 [28  4 89 58 21 52 33 68 16 87]
 [10 43 29 47 44 99 52 17 28 72]]


In [56]:
print(np.min(stats)==np.amin(stats)),np.min(stats),np.amin(stats)   #np.min=np.amin

True


(None, 2, 2)

In [57]:
print(np.max(stats)==np.amax(stats) ),np.max(stats),np.amax(stats)  #np.max=np.amax

True


(None, 99, 99)

In [58]:
print('Minimum value of the array --->',np.min(stats))
print('\nMaximum value of the array --->',np.max(stats))
print('\nMean --->',np.mean(stats))
print('\nMedian --->',np.median(stats))
print('\nVariance --->',np.var(stats))
print('\nStandard Deviation --->',np.std(stats))
print('\nPercentile --->',np.percentile(stats,[25,50,75]),'(25th Percentile(Q1),50th Percentile(median or Q2),75th Percentile(Q3))')

Minimum value of the array ---> 2

Maximum value of the array ---> 99

Mean ---> 53.5

Median ---> 55.5

Variance ---> 704.69

Standard Deviation ---> 26.5459978151133

Percentile ---> [30.5  55.5  74.75] (25th Percentile(Q1),50th Percentile(median or Q2),75th Percentile(Q3))


#### Inter-Quartile Range

In [59]:
quartiles=np.percentile(stats,[25,75])
iqr=quartiles[1]-quartiles[0]
print('Inter-Quartile Range --->',iqr)

Inter-Quartile Range ---> 44.25


#### Z-Score

In [60]:
z_score=(stats/np.mean(stats))/np.std(stats)
print('Z-Score --->',z_score)

Z-Score ---> [[0.02394011 0.0506967  0.05492142 0.00140824 0.0577379  0.00140824
  0.0337978  0.01197005 0.0506967  0.00704121]
 [0.04154313 0.06125851 0.01197005 0.04365549 0.03872664 0.03943076
  0.02394011 0.02182774 0.0204195  0.04999258]
 [0.03872664 0.04506373 0.04928845 0.03450192 0.05703378 0.00985769
  0.04435961 0.04154313 0.05140082 0.05140082]
 [0.04928845 0.06196263 0.02464423 0.05844203 0.05914615 0.03591016
  0.02675659 0.06477911 0.06829972 0.0373184 ]
 [0.02464423 0.04154313 0.03661428 0.03027719 0.00844945 0.04224725
  0.03520604 0.03661428 0.0542173  0.02253187]
 [0.04576785 0.03027719 0.06125851 0.06829972 0.05844203 0.04365549
  0.03309368 0.01408242 0.01901126 0.04576785]
 [0.05632966 0.01760302 0.06055439 0.01056181 0.0577379  0.01056181
  0.01408242 0.01408242 0.06125851 0.05632966]
 [0.06477911 0.0577379  0.01337829 0.05844203 0.06618735 0.01056181
  0.04506373 0.05210494 0.04999258 0.04999258]
 [0.01971538 0.00281648 0.06266675 0.04083901 0.01478654 0.03661428

# **_AXIS IN MUTI-DIMENSIONAL ARRAY_**

**While working with Multi-dimensional array specifying the axis gives the appropriate answer based on row-wise or columnwise.For each and every dimension the ordering of axis changes as show in the below figure**

![](ndarr.jpg)

In [61]:
stats

array([[34, 72, 78,  2, 82,  2, 48, 17, 72, 10],
       [59, 87, 17, 62, 55, 56, 34, 31, 29, 71],
       [55, 64, 70, 49, 81, 14, 63, 59, 73, 73],
       [70, 88, 35, 83, 84, 51, 38, 92, 97, 53],
       [35, 59, 52, 43, 12, 60, 50, 52, 77, 32],
       [65, 43, 87, 97, 83, 62, 47, 20, 27, 65],
       [80, 25, 86, 15, 82, 15, 20, 20, 87, 80],
       [92, 82, 19, 83, 94, 15, 64, 74, 71, 71],
       [28,  4, 89, 58, 21, 52, 33, 68, 16, 87],
       [10, 43, 29, 47, 44, 99, 52, 17, 28, 72]])

In [62]:
print('Columwise Minimum --->',np.min(stats,axis=0))
print('\nRowwise Minimum\n',np.max(stats,axis=1).reshape(10,1)) # 2Dimensional Array axis=0(columwise) & axis=1(rowwise)

Columwise Minimum ---> [10  4 17  2 12  2 20 17 16 10]

Rowwise Minimum
 [[82]
 [87]
 [81]
 [97]
 [77]
 [97]
 [87]
 [94]
 [89]
 [99]]


In [63]:
print('Columwise Mean --->',np.mean(stats,axis=0))
print('\nRowwise Mean\n',np.mean(stats,axis=1).reshape(10,1))

Columwise Mean ---> [52.8 56.7 56.2 53.9 63.8 42.6 44.9 45.  57.7 61.4]

Rowwise Mean
 [[41.7]
 [50.1]
 [60.1]
 [69.1]
 [47.2]
 [59.6]
 [51. ]
 [66.5]
 [45.6]
 [44.1]]


In [64]:
print('Columwise Sum --->',np.sum(stats,axis=0))
print('\nRowwise Sum\n',np.sum(stats,axis=1).reshape(10,1))

Columwise Sum ---> [528 567 562 539 638 426 449 450 577 614]

Rowwise Sum
 [[417]
 [501]
 [601]
 [691]
 [472]
 [596]
 [510]
 [665]
 [456]
 [441]]


## Limitations of NumPy

* *There is no way to attach labels to data.*
* *There is no pre-built methods to fill missing values.*
* *There is no way to group data.*
* *There is no way to Pivot data.*

**_Thus to overcome these limitations we use Pandas package._**

-----------------------------------------------------------------------------------------THE END---------------------------------------------------------------------------------------